### ISSUE TITLE
Unique Constraing Violation when analyzing an existing project under another name

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#175]
Caused by: org.postgresql.util.PSQLException: FEHLER: doppelter Schl├╝sselwert verletzt Unique-Constraint ┬╗uk_comm_name┬½
  Detail: Schl├╝ssel ┬╗(name)=(2cec6d1aa13db74415dcbb401f47f06d7ef17544)┬½ existiert bereits.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:135) ~[postgresql-9.4.1212.jar:9.4.1212]
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204) ~[hibernate-core-5.2.3.Final.jar:5.2.3.Final]
        ... 49 common frames omitted

**Comment by rzpio** [comment]
Will not be fixed anymore, because we soon switch to Neo4j.
