### ISSUE TITLE
Continous NullPointerException

### ISSUE THREAD

**Issue by JonGoe** [reflectoring/coderadar#179]
java.lang.NullPointerException: null
        at org.wickedsource.coderadar.job.core.FirstCommitFinder.isFirstCommitInProject(FirstCommitFinder.java:27) ~[classes!/:na]
        at org.wickedsource.coderadar.job.scan.file.FileMetadataScanner.scan(FileMetadataScanner.java:92) ~[classes!/:na]
        at org.wickedsource.coderadar.job.execute.JobExecutor.execute(JobExecutor.java:50) ~[classes!/:na]
        at org.wickedsource.coderadar.job.execute.JobExecutor$$FastClassBySpringCGLIB$$a1756041.invoke(<generated>) ~[classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) [spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) [spring-tx-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) [spring-tx-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) [spring-tx-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) [spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.wickedsource.coderadar.job.execute.JobExecutor$$EnhancerBySpringCGLIB$$5c33bfe4.execute(<generated>) ~[classes!/:na]
        at org.wickedsource.coderadar.job.execute.JobExecutionService.executeNextJobInQueue(JobExecutionService.java:61) ~[classes!/:na]
        at org.wickedsource.coderadar.job.execute.JobExecutionService$$FastClassBySpringCGLIB$$b12d41eb.invoke(<generated>) [classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) [spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) [spring-tx-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(Transa

**Comment by maximAtanasov** [comment]
No longer an issue after the refactoring.
