### ISSUE TITLE
Token expiration exception stacktrace should not be logged

### ISSUE THREAD

**Issue by maximAtanasov** [reflectoring/coderadar#234]
```
com.auth0.jwt.exceptions.InvalidClaimException: The Token has expired on Mon Mar 18 15:24:14 CET 2019.
        at com.auth0.jwt.JWTVerifier.assertValidDateClaim(JWTVerifier.java:434) ~[java-jwt-3.1.0.jar:na]
        at com.auth0.jwt.JWTVerifier.verifyClaims(JWTVerifier.java:366) ~[java-jwt-3.1.0.jar:na]
        at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:342) ~[java-jwt-3.1.0.jar:na]
        at org.wickedsource.coderadar.security.service.TokenService.verify(TokenService.java:68) ~[main/:na]
        at org.wickedsource.coderadar.security.AuthenticationTokenFilter.doFilterInternal(AuthenticationTokenFilter.java:46) ~[main/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96) [spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74) [spring-security-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.4.RELEASE.jar:5.1.4.RELEASE]
```

**Comment by maximAtanasov** [comment]
No longer an issue in master (after new-architecture merge). See #292 and #282
